### ISSUE TITLE
Error in Xcode 14 beta via Cocoapods

### ISSUE THREAD

**Issue by akovalov** [pmusolino/Wormholy#117]
Installed Wormholy v1.6.5 via Cocoapods
Xcode Version 14.0 beta (14A5228q)

<img width="299" alt="Screenshot 2022-06-23 at 10 53 17" src="https://user-images.githubusercontent.com/9693643/175246785-4ef83c41-d6ba-483c-a598-d9ab7d226a35.png">

Other dependencies do not trigger such error. Removing Wormholy resolves the issue. 

Adding Wormholy via Swift Package Manager in both Xcode 14 beta and Xcode 13 shows that package could not be resolved.

**Comment by akovalov** [comment]
For some reason on install Cocoapods generate an extra "Wormholy-Wormholy" target that looks like an app target, so requires signing. It can be removed and the issue is resolved. Howerver, on the next `pod install` it will appear again.

**Comment by pmusolino** [comment]
Can you show me how you are importing Wormholy in your Podfile?

**Comment by akovalov** [comment]
@pmusolino 
```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

use_frameworks!
inhibit_all_warnings!

pod 'Wormholy'

target 'Some' do
  
end

```

**Comment by SwiftFoxx** [comment]
@akovalov 
Your Podfile syntax looks incorrect. It should be

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

target 'Some' do
use_frameworks!
inhibit_all_warnings!

  pod 'Wormholy'
  
end
```

Even though I tried installing this library with this syntax, I encountered an error. Dumping the log below:
```
LoadError - dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle, 0x0009): tried: '/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (no such file), '/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')) - /Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi.rb:5:in `rescue in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.15.5/lib/ffi.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ethon-0.15.0/lib/ethon.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:338:in `download_file'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:284:in `ensure_versions_file_loaded'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/cdn_source.rb:208:in `search'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.11.3/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:165:in `search_for'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_by'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_by!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:288:in `push_initial_state'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:210:in `start_resolution'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:168:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/resolver.rb:94:in `resolve'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1078:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:1076:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:416:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:241:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:240:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/installer.rb:161:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.11.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by akovalov** [comment]
@SwiftFoxx the Podfile syntax is correct, it uses "implicit abstract target" notation like described here https://guides.cocoapods.org/using/the-podfile.html. 

The issue I've reported is that it's not working in Xcode 14 beta due to an extra target generated, but it works fine with Xcode 13.

**Comment by SwiftFoxx** [comment]
@akovalov I understand your query now. I installed the pod in `xcode 14 beta`. Didn't see any extra target and the project built fine.
I'm sorry, I have no idea what's the issue you're facing.

**Comment by akovalov** [comment]
@SwiftFoxx I've tried now with the latest Xcode 14.0 beta 2 (14A5229c) and the issue is still there. It looks like the same issue described here https://github.com/CocoaPods/CocoaPods/issues/11402. I now see that it's not an extra target, that target is for Wormholy to work properly. But the issue is that it requires a team for signing, which looks like an Xcode 14 or Cocoapods issues. However, I am wondering why there is no error on your machine. When I choose a team for this target - it works.

<img width="1488" alt="Screenshot 2022-06-29 at 15 43 05" src="https://user-images.githubusercontent.com/9693643/176440142-8e1b3f80-cd79-45e3-a863-9a29fe3510ec.png">

**Comment by SwiftFoxx** [comment]
@akovalov I deleted and created a new test project. This time the target appeared. Positive.
So, I was curious why it was appearing. I inspected the `.podspec` file and concluded it's the `resources` bundle needed to copy non-source files into the pod target. But it should not have asked for a team for signing.
So, seems like it's a problem triggered by M1 onwards devices. Ruby and Cocoapods may well be deprecated and all of the project may require to use SPM for libraries. It's cocoapod's problem and in essence Ruby's problem that the target and signing are not handled properly.
So, either we have to add the developer team or have to use SPM.

**Comment by akovalov** [comment]
@SwiftFoxx looks like  you are right. In this case  it would be fine using Wormholy via SPM but there is an error installing it via SPM as well.

**Comment by iwheelbuy** [comment]
post_install do |installer|
  #
  # Fixing resources signing for xcode 14 sdk
  #
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['WRAPPER_EXTENSION'] == 'bundle'
        config.build_settings['DEVELOPMENT_TEAM'] = 'YOU_TEAM_ID'
      end
    end
  end
end

**Comment by heliang219** [comment]
Is there any other method to solve this error? not write script, only pod install. Maybe author can update "Wormholy" to fix the program we meet.

**Comment by akovalov** [comment]
@heliang219 I use the `post_install` like described above in https://github.com/pmusolino/Wormholy/issues/117#issuecomment-1265199547 and it works ok. It also work for any other library that has this thing.

**Comment by siki88** [comment]
```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 i386"

      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
```

**Comment by pmusolino** [comment]
Could you try to test it with the latest version 1.7.0?
